on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/tofu-plan-apply.yml
    strategy:
      fail-fast: false
      matrix:
        environment:
          - prod
          # TODO: Need to figure out github permissions 
          # - bootstrap
    with:
      environment: ${{ matrix.environment }}
